// ============================================================================
// Zephyria — VM Bridge (Production — Thread-Safe)
// ============================================================================
//
// Connects the RISC-V RV32EM VM (forgec/vm/) to the Zephyria node executor
// as the primary smart contract execution backend.
//
// This bridge:
//   • Creates a StateBridge per call (connects VM syscalls → State Overlay)
//   • Passes full execution context (block/tx env) from executor to VM
//   • Propagates logs from HostEnv back to the executor for receipts
//   • Returns contract output (returnData) for external visibility
//
// Thread Safety:
//   The VM operates within the per-TX Overlay isolation model. Each lane in
//   the DAG executor creates its own Overlay. The VMBridge is thread-safe
//   because execution context is passed through the callback's ctx pointer
//   (not global state). Multiple lanes can invoke VM concurrently.
//
// Isolation Model:
//   - Each TX gets its own Overlay (snapshot of world state)
//   - All state changes within a call tree are isolated to that Overlay
//   - On success, the Overlay commits atomically to the world state
//   - Different TXs in different lanes have zero conflicts (guaranteed by DAG scheduler)

const std = @import("std");
const core = @import("core");
const VMCallback = core.dag_executor.VMCallback;
const VMResult = core.dag_executor.VMResult;
const state_mod = core.state;
const state_bridge = @import("state_bridge");
const StateBridge = state_bridge.StateBridge;

/// VMBridge configuration
/// Configuration options for the VMBridge.
pub const VMConfig = struct {
    enableJit: bool = false, // Reserved for future RISC-V JIT
    optimizationLevel: OptLevel = .Fast,
    traceExecution: bool = false,
    gasLimit: u64 = 30_000_000,
    /// Execution timeout per contract call (ms)
    executionTimeoutMs: u64 = 5_000,
};

/// Optimization levels for the RISC-V VM execution.
pub const OptLevel = enum {
    None,
    Fast,
    Small,
};

/// Execution context passed from the executor for each block/TX.
/// Provides block-level and transaction-level environment values
/// that contracts can query via syscalls.
/// Execution context passed from the executor for each block/TX.
/// Provides block-level and transaction-level environment values
/// that contracts can query via syscalls.
pub const ExecutionContext = struct {
    /// Block timestamp (seconds since Unix epoch)
    timestamp: u64 = 0,
    /// Transaction originator (tx.origin)
    txOrigin: [20]u8 = [_]u8{0} ** 20,
    /// Transaction gas price
    gasPrice: u64 = 0,
    /// Block coinbase (validator address from consensus)
    coinbase: [20]u8 = [_]u8{0} ** 20,
    /// Block base fee (EIP-1559)
    baseFee: u64 = 0,
    /// Block prevRandao (VRF output from adaptive consensus)
    prevRandao: [32]u8 = [_]u8{0} ** 32,
    /// Block number
    blockNumber: u64 = 0,
    /// Chain ID
    chainId: u64 = 99999,
};

/// Log data generated by contract execution (for receipts).
/// Log data generated by contract execution (for receipts).
pub const LogData = struct {
    address: [20]u8,
    topics: [][32]u8,
    data: []u8,
};

/// VMBridge provides the integration layer between the Zephyria node executor
/// and the RISC-V VM for contract execution.
///
/// Thread-Safe Design:
///   The VMBridge instance stores the execution context (set per-block).
///   The executeCallback reads context atomically through the ctx pointer.
///   No global mutable state — the bridge pointer is passed through VMCallback.ctx.
/// VMBridge provides the integration layer between the Zephyria node executor
/// and the RISC-V VM for contract execution.
///
/// Thread-Safe Design:
///   The VMBridge instance stores the execution context (set per-block).
///   The executeCallback reads context atomically through the ctx pointer.
///   No global mutable state — the bridge pointer is passed through VMCallback.ctx.
pub const VMBridge = struct {
    allocator: std.mem.Allocator,
    config: VMConfig,
    executionCount: std.atomic.Value(u64),
    totalGasUsed: std.atomic.Value(u64),
    /// Current execution context (set per-block by the miner/block producer)
    /// Read by parallel lanes — set once before block execution, immutable during.
    execCtx: ExecutionContext,

    /// Initializes a new VMBridge instance.
    pub fn init(allocator: std.mem.Allocator, config: VMConfig) VMBridge {
        return .{
            .allocator = allocator,
            .config = config,
            .executionCount = std.atomic.Value(u64).init(0),
            .totalGasUsed = std.atomic.Value(u64).init(0),
            .execCtx = .{},
        };
    }

    /// Deinitializes the VMBridge instance.
    pub fn deinit(self: *VMBridge) void {
        _ = self;
    }

    /// Set execution context for the current block.
    /// Called by the miner/block producer BEFORE block execution starts.
    /// Must not be called while lanes are executing.
    /// Sets the execution context for the current block.
    /// This should be called before block execution begins and remains constant during the block.
    pub fn setExecutionContext(self: *VMBridge, ctx: ExecutionContext) void {
        self.execCtx = ctx;
    }

    /// Returns a VMCallback compatible with both core.executor and core.dag_executor.
    /// The VMBridge pointer is passed through ctx — no global state needed.
    /// Returns a VMCallback compatible with both core.executor and core.dag_executor.
    pub fn getCallback(self: *VMBridge) VMCallback {
        return VMCallback{
            .ctx = @ptrCast(self),
            .exec_fn = &executeCallback,
        };
    }

    /// Returns a legacy VMCallback compatible with core.executor.VMCallback.
    /// Uses the same underlying function but cast to the legacy type.
    /// Returns a legacy VMCallback compatible with core.executor.VMCallback.
    pub fn getLegacyCallback(self: *VMBridge) core.executor.VMCallback {
        return core.executor.VMCallback{
            .ctx = @ptrCast(self),
            .exec_fn = @ptrCast(&executeCallback),
        };
    }

    /// Get execution statistics (thread-safe reads)
    /// Returns thread-safe execution statistics (total count and gas used).
    pub fn getStats(self: *const VMBridge) struct { count: u64, gas: u64 } {
        return .{
            .count = self.executionCount.load(.monotonic),
            .gas = self.totalGasUsed.load(.monotonic),
        };
    }

    /// Execute a contract via RISC-V VM — the main execution callback.
    /// Called by the executor for both contract calls and deployments.
    ///
    /// Thread Safety: The VMBridge pointer is extracted from ctx — no global state.
    /// Each lane passes its own overlay, so there are zero cross-lane data races.
    ///
    /// This function:
    ///   1. Creates a StateBridge connecting VM syscalls → State Overlay
    ///   2. Passes full block/TX execution context
    ///   3. Executes the RISC-V bytecode
    ///   4. Propagates logs from HostEnv to VMResult
    ///   5. Returns output (returnData) for the executor
    fn executeCallback(
        ctx: *anyopaque,
        code: []const u8,
        input: []const u8,
        gas: u64,
        overlay: *state_mod.Overlay,
        caller: core.types.Address,
        value: u256,
    ) VMResult {
        // Thread-safe: extract VMBridge from ctx pointer, no global state
        const bridge: *VMBridge = @ptrCast(@alignCast(ctx));
        _ = bridge.executionCount.fetchAdd(1, .monotonic);

        // Empty code = nothing to execute
        if (code.len == 0) {
            return VMResult{
                .success = true,
                .gasUsed = 0,
                .returnData = &[_]u8{},
            };
        }

        // Create a StateBridge connecting the VM syscalls to the State overlay.
        // The overlay provides per-TX isolation — all state changes are
        // scoped to this overlay until the executor commits or reverts.
        var sb = StateBridge.init(
            bridge.allocator,
            @ptrCast(overlay),
            caller.bytes, // self_address (contract being called)
            caller.bytes, // caller (msg.sender)
            u256ToBytes(value), // call value
            gas,
        );
        defer sb.deinit();

        // Wire full execution context from the block/TX environment
        // These are set once per block and immutable during lane execution
        sb.blockNumber = bridge.execCtx.blockNumber;
        sb.timestamp = bridge.execCtx.timestamp;
        sb.chainId = bridge.execCtx.chainId;
        sb.txOrigin = bridge.execCtx.txOrigin;
        sb.gasPrice = bridge.execCtx.gasPrice;
        sb.coinbase = bridge.execCtx.coinbase;
        sb.baseFee = bridge.execCtx.baseFee;
        sb.prevRandao = bridge.execCtx.prevRandao;

        // Execute via RISC-V VM with all providers wired
        const riscv = @import("vm/riscv/mod.zig");
        const exec_result = riscv.executeContract(
            bridge.allocator,
            code,
            input,
            gas,
            @ptrCast(&sb),
        ) catch {
            return VMResult{
                .success = false,
                .gasUsed = gas,
                .returnData = &[_]u8{},
            };
        };

        _ = bridge.totalGasUsed.fetchAdd(exec_result.gasUsed, .monotonic);

        const ret_buf = if (exec_result.returnData.len > 0)
            bridge.allocator.dupe(u8, exec_result.returnData) catch &[_]u8{}
        else
            &[_]u8{};

        return VMResult{
            .success = exec_result.success,
            .gasUsed = exec_result.gasUsed,
            .returnData = ret_buf,
        };
    }
};

fn u256ToBytes(value: u256) [32]u8 {
    var bytes: [32]u8 = [_]u8{0} ** 32;
    var v = value;
    var i: usize = 31;
    while (v > 0) : (i -= 1) {
        bytes[i] = @truncate(v & 0xFF);
        v >>= 8;
        if (i == 0) break;
    }
    return bytes;
}
