// File: tools/sol2zig/codegen.zig
// Zig source code generator from Solidity AST
// Produces Zephyria SDK-compatible Zig source with full expression/statement transpilation

const std = @import("std");
const parser = @import("parser.zig");
const type_mapper = @import("type_mapper.zig");
const ast = @import("ast.zig");
const ExprParser = @import("expr_parser.zig").ExprParser;
const selector = @import("selector.zig");

pub const CodeGenerator = struct {
    allocator: std.mem.Allocator,
    parsed_ast: *const parser.SolidityAST,
    type_map: []const type_mapper.TypeMapping,
    output: std.ArrayListUnmanaged(u8),
    indent_level: usize,
    /// Names of current contract's state variables (set during generateContract)
    current_state_vars: []const []const u8,
    /// Solidity types of current contract's state variables (parallel to current_state_vars)
    current_state_var_types: []const []const u8,
    /// True when emitting the LHS of an assignment (suppress .load() for state vars)
    emitting_assign_target: bool,
    /// Track already-emitted top-level custom error names to avoid duplicates
    emitted_errors: std.StringHashMap(void),
    /// Names of functions in the current contract (for detecting internal calls)
    current_contract_functions: []const []const u8,
    /// Number of contracts from the original source (before imports were appended)
    original_contract_count: usize,
    /// Parameter renames for the current function (original -> renamed)
    /// Used to avoid Zig parameter shadowing of struct function names
    param_renames: std.StringHashMap([]const u8),

    pub fn init(
        allocator: std.mem.Allocator,
        parsed_ast: *const parser.SolidityAST,
        type_map: []const type_mapper.TypeMapping,
    ) CodeGenerator {
        return .{
            .allocator = allocator,
            .parsed_ast = parsed_ast,
            .type_map = type_map,
            .output = .{},
            .indent_level = 0,
            .current_state_vars = &.{},
            .current_state_var_types = &.{},
            .emitting_assign_target = false,
            .emitted_errors = std.StringHashMap(void).init(allocator),
            .current_contract_functions = &.{},
            .original_contract_count = 0,
            .param_renames = std.StringHashMap([]const u8).init(allocator),
        };
    }

    pub fn deinit(self: *CodeGenerator) void {
        self.output.deinit(self.allocator);
        self.emitted_errors.deinit();
        // Free duped rename strings
        var it = self.param_renames.valueIterator();
        while (it.next()) |val| {
            self.allocator.free(val.*);
        }
        self.param_renames.deinit();
    }

    pub fn generate(self: *CodeGenerator) ![]const u8 {
        try self.emitLine("// Auto-generated by sol2zig — Zephyria Solidity-to-Zig Transpiler");
        try self.emitLine("// Do not edit manually");
        try self.emitLine("");
        try self.emitLine("const sdk = @import(\"zephyria-sdk\");");
        try self.emitLine("const Uint256 = sdk.Uint256;");
        try self.emitLine("const Int256 = sdk.Int256;");
        try self.emitLine("const Address = sdk.Address;");
        try self.emitLine("const Bytes32 = sdk.Bytes32;");
        try self.emitLine("");

        // Only emit the main contracts from the original source file.
        // Imported base contracts (ERC20, Ownable, etc.) are merged into the
        // main contract via inheritance and should not be emitted separately.
        const count = if (self.original_contract_count > 0)
            @min(self.original_contract_count, self.parsed_ast.contracts.items.len)
        else
            self.parsed_ast.contracts.items.len;
        for (self.parsed_ast.contracts.items[0..count]) |contract| {
            try self.generateContract(contract);
            try self.emitLine("");
        }

        return self.output.items;
    }

    fn generateContract(self: *CodeGenerator, contract: parser.ContractDef) !void {
        try self.emit("// Contract: ");
        try self.emitLine(contract.name);

        for (contract.enums.items) |e| try self.generateEnum(e);
        for (contract.structs.items) |s| try self.generateStruct(s);
        for (contract.errors_list.items) |err| try self.generateCustomError(err);

        try self.emit("pub const ");
        try self.emit(contract.name);
        try self.emitLine(" = struct {");
        self.indent_level += 1;

        // Collect state variable names and types for self-prefixing in function bodies
        var sv_names: std.ArrayListUnmanaged([]const u8) = .{};
        defer sv_names.deinit(self.allocator);
        var sv_types: std.ArrayListUnmanaged([]const u8) = .{};
        defer sv_types.deinit(self.allocator);
        for (contract.state_variables.items) |sv| {
            if (sv.mutability != .constant) {
                try sv_names.append(self.allocator, sv.name);
                try sv_types.append(self.allocator, sv.type_name);
            }
        }
        self.current_state_vars = sv_names.items;
        self.current_state_var_types = sv_types.items;

        // Collect function names for internal call detection
        var fn_names: std.ArrayListUnmanaged([]const u8) = .{};
        defer fn_names.deinit(self.allocator);
        for (contract.functions.items) |func| {
            if (func.name.len > 0) {
                try fn_names.append(self.allocator, func.name);
            }
        }
        self.current_contract_functions = fn_names.items;

        // State variables
        for (contract.state_variables.items) |sv| try self.generateStateVariable(sv);
        if (contract.state_variables.items.len > 0) try self.emitLine("");

        // Events
        for (contract.events.items) |event| try self.generateEvent(event);
        if (contract.events.items.len > 0) try self.emitLine("");

        // Functions
        for (contract.functions.items) |func| {
            switch (func.kind) {
                .constructor => try self.generateConstructor(func),
                .receive => try self.generateSpecialFunction("receive", func),
                .fallback => try self.generateSpecialFunction("fallback", func),
                .function => try self.generateFunction(func),
            }
            try self.emitLine("");
        }

        // Note: Auto-generated getters removed — field declarations serve as schema
        // Access state via self.field.load(ctx.storage_backend) / self.field.store(ctx.storage_backend, val)

        // Phase 5: Storage layout comment
        try self.generateStorageLayout(contract);

        // Phase 5: Dispatch table
        try self.generateDispatchTable(contract);

        self.indent_level -= 1;
        try self.emitLine("};");
    }

    fn generateStateVariable(self: *CodeGenerator, sv: parser.StateVarDef) !void {
        try self.emitIndent();
        if (sv.mutability == .constant) {
            try self.emit("pub const ");
            try self.emit(sv.name);
            try self.emit(": ");
            try self.emit(type_mapper.mapType(sv.type_name));
            if (sv.initial_value) |val| {
                try self.emit(" = ");
                // Wrap numeric constant values for Uint256/Int256 types
                const mapped_type = type_mapper.mapType(sv.type_name);
                if (std.mem.eql(u8, mapped_type, "sdk.Uint256") or std.mem.eql(u8, mapped_type, "Uint256")) {
                    try self.emitUint256Constant(val);
                } else if (std.mem.eql(u8, mapped_type, "sdk.Int256") or std.mem.eql(u8, mapped_type, "Int256")) {
                    try self.emitUint256Constant(val);
                } else {
                    try self.emitRawExpression(val);
                }
            }
            try self.emitLine(";");
        } else {
            try self.emit(sv.name);
            try self.emit(": ");
            // Resolve mapping types to sdk.StorageMapping(K, V)
            const storage_type = type_mapper.mapStorageType(sv.type_name);
            if (std.mem.eql(u8, storage_type, "Mapping")) {
                try self.emitMappingType(sv.type_name);
            } else {
                try self.emit(storage_type);
            }
            try self.emitLine(",");
        }
    }

    fn generateEvent(self: *CodeGenerator, event: parser.EventDef) !void {
        try self.emitIndent();
        try self.emit("pub const ");
        try self.emit(event.name);
        try self.emit(" = sdk.Event(\"");
        try self.emit(event.name);
        try self.emit("\", .{");
        for (event.params.items, 0..) |param, i| {
            if (i > 0) try self.emit(", ");
            try self.emit("\n");
            try self.emitIndent();
            try self.emit("    .{ .name = \"");
            try self.emit(param.name);
            try self.emit("\", .type_name = \"");
            try self.emit(type_mapper.mapType(param.type_name));
            try self.emit("\", .indexed = ");
            if (param.is_indexed) try self.emit("true") else try self.emit("false");
            try self.emit(" }");
        }
        try self.emitLine(",");
        try self.emitIndent();
        try self.emitLine("});");
    }

    fn generateConstructor(self: *CodeGenerator, ctor: parser.FunctionDef) !void {
        try self.emitIndent();
        try self.emit("pub fn init(self: *@This(), ctx: *sdk.ExecutionContext");
        for (ctor.params.items) |param| {
            try self.emit(", ");
            try self.emitParamName(param.name);
            try self.emit(": ");
            try self.emit(type_mapper.mapType(param.type_name));
        }
        try self.emitLine(") void {");
        self.indent_level += 1;
        if (ctor.body) |body| {
            try self.emitTranspiledBody(body);
        } else {
            try self.emitUnused("self");
            try self.emitUnused("ctx");
        }
        self.indent_level -= 1;
        try self.emitIndent();
        try self.emitLine("}");
    }

    fn generateFunction(self: *CodeGenerator, func: parser.FunctionDef) !void {
        // Clear param renames from previous function, freeing duped strings
        {
            var it = self.param_renames.valueIterator();
            while (it.next()) |val| {
                self.allocator.free(val.*);
            }
            self.param_renames.clearRetainingCapacity();
        }

        try self.emitIndent();
        try self.emit("pub fn ");
        try self.emit(func.name);
        try self.emit("(self: *@This(), ctx: *sdk.ExecutionContext");
        for (func.params.items) |param| {
            try self.emit(", ");
            // Rename params that shadow function names in the same contract
            const param_name = if (param.name.len > 0) param.name else "_";
            if (self.isContractFunction(param_name)) {
                // Build renamed param using arena-duped buffer
                var rename_buf: [128]u8 = undefined;
                const renamed = std.fmt.bufPrint(&rename_buf, "{s}_param", .{param_name}) catch param_name;
                const renamed_dupe = self.allocator.dupe(u8, renamed) catch param_name;
                try self.param_renames.put(param_name, renamed_dupe);
                try self.emit(renamed_dupe);
            } else {
                try self.emit(param_name);
            }
            try self.emit(": ");
            try self.emit(type_mapper.mapType(param.type_name));
        }
        try self.emit(") ");

        // Return type
        if (func.returns.items.len == 0) {
            try self.emit("void");
        } else if (func.returns.items.len == 1) {
            try self.emit(type_mapper.mapType(func.returns.items[0].type_name));
        } else {
            try self.emit("struct { ");
            for (func.returns.items, 0..) |ret, i| {
                if (i > 0) try self.emit(", ");
                if (ret.name.len > 0) {
                    try self.emit(ret.name);
                } else {
                    try self.emit(std.fmt.allocPrint(self.allocator, "_{d}", .{i}) catch "val");
                }
                try self.emit(": ");
                try self.emit(type_mapper.mapType(ret.type_name));
            }
            try self.emit(" }");
        }

        try self.emitLine(" {");
        self.indent_level += 1;

        // Emit modifier guards (inline the modifier body)
        for (func.modifiers_applied.items) |mod_call| {
            try self.emitIndent();
            // Map well-known modifiers to their guard functions
            if (std.mem.eql(u8, mod_call.name, "onlyOwner")) {
                try self.emitLine("self._checkOwner(ctx);");
            } else {
                // Generic modifier: call the check function
                try self.emit("self._check");
                // Capitalize first letter
                if (mod_call.name.len > 0) {
                    var buf: [1]u8 = .{std.ascii.toUpper(mod_call.name[0])};
                    try self.emit(&buf);
                    if (mod_call.name.len > 1) {
                        try self.emit(mod_call.name[1..]);
                    }
                }
                try self.emitLine("(ctx);");
            }
        }

        // Emit transpiled body, capturing output to detect unused params
        if (func.body) |body| {
            const body_start = self.output.items.len;
            try self.emitTranspiledBody(body);
            const body_output = self.output.items[body_start..];
            // Check if self/ctx are used in the emitted body
            const uses_self = std.mem.indexOf(u8, body_output, "self.") != null;
            const uses_ctx = std.mem.indexOf(u8, body_output, "ctx.") != null or
                std.mem.indexOf(u8, body_output, "ctx)") != null or
                std.mem.indexOf(u8, body_output, "ctx,") != null;
            // Insert unused param suppressions BEFORE the body if needed
            if (!uses_self or !uses_ctx) {
                // We need to insert at body_start position
                var suppress_buf: [64]u8 = undefined;
                var suppress_len: usize = 0;
                if (!uses_self) {
                    const s = "    _ = self;\n";
                    @memcpy(suppress_buf[suppress_len..][0..s.len], s);
                    suppress_len += s.len;
                }
                if (!uses_ctx) {
                    const s = "    _ = ctx;\n";
                    @memcpy(suppress_buf[suppress_len..][0..s.len], s);
                    suppress_len += s.len;
                }
                if (suppress_len > 0) {
                    try self.output.insertSlice(self.allocator, body_start, suppress_buf[0..suppress_len]);
                }
            }
        } else {
            // Interface/abstract functions have no body
            if (func.returns.items.len > 0) {
                // Must return a value — emit @panic for unimplemented functions
                try self.emitIndent();
                try self.emitLine("@panic(\"not implemented\");");
            } else {
                try self.emitUnused("self");
                try self.emitUnused("ctx");
            }
        }

        self.indent_level -= 1;
        try self.emitIndent();
        try self.emitLine("}");
    }

    fn generateSpecialFunction(self: *CodeGenerator, name: []const u8, func: parser.FunctionDef) !void {
        try self.emitIndent();
        try self.emit("pub fn ");
        try self.emit(name);
        if (std.mem.eql(u8, name, "fallback")) {
            try self.emitLine("(self: *@This(), ctx: *sdk.ExecutionContext, calldata: []const u8) []const u8 {");
        } else {
            try self.emitLine("(self: *@This(), ctx: *sdk.ExecutionContext) void {");
        }
        self.indent_level += 1;
        if (func.body) |body| {
            try self.emitTranspiledBody(body);
        } else {
            try self.emitUnused("self");
            try self.emitUnused("ctx");
        }
        self.indent_level -= 1;
        try self.emitIndent();
        try self.emitLine("}");
    }

    fn generateStruct(self: *CodeGenerator, s: parser.StructDef) !void {
        try self.emit("pub const ");
        try self.emit(s.name);
        try self.emitLine(" = struct {");
        self.indent_level += 1;
        for (s.fields.items) |field| {
            try self.emitIndent();
            try self.emit(field.name);
            try self.emit(": ");
            try self.emit(type_mapper.mapType(field.type_name));
            try self.emitLine(",");
        }
        self.indent_level -= 1;
        try self.emitLine("};");
        try self.emitLine("");
    }

    fn generateEnum(self: *CodeGenerator, e: parser.EnumDef) !void {
        try self.emit("pub const ");
        try self.emit(e.name);
        try self.emitLine(" = enum(u8) {");
        self.indent_level += 1;
        for (e.members.items) |member| {
            try self.emitIndent();
            try self.emit(member);
            try self.emitLine(",");
        }
        self.indent_level -= 1;
        try self.emitLine("};");
        try self.emitLine("");
    }

    fn generateCustomError(self: *CodeGenerator, err: parser.ErrorDef) !void {
        // Skip duplicate custom errors (can happen when multiple contracts inherit the same errors)
        if (self.emitted_errors.contains(err.name)) return;
        self.emitted_errors.put(err.name, {}) catch {};
        try self.emit("pub const ");
        try self.emit(err.name);
        try self.emit(" = sdk.CustomError(\"");
        try self.emit(err.name);
        try self.emit("\", struct { ");
        for (err.params.items, 0..) |param, i| {
            if (i > 0) try self.emit(", ");
            if (param.name.len > 0) {
                try self.emit(param.name);
            } else {
                try self.emit(std.fmt.allocPrint(self.allocator, "_{d}", .{i}) catch "val");
            }
            try self.emit(": ");
            try self.emit(type_mapper.mapType(param.type_name));
        }
        try self.emitLine(" });");
    }

    // ========================================================================
    // PHASE 2: Transpiled Body Emission (Expression AST → Zig Code)
    // ========================================================================

    fn emitTranspiledBody(self: *CodeGenerator, body: []const u8) !void {
        // Use a scoped arena for all ExprParser allocations (AST nodes, slices).
        // The arena is freed after statement emission, preventing all expr_parser leaks.
        var expr_arena = std.heap.ArenaAllocator.init(self.allocator);
        defer expr_arena.deinit();

        var ep = ExprParser.init(expr_arena.allocator(), body);
        const stmts = ep.parseBlock() catch {
            // Fallback to raw emission with comments
            try self.emitRawBody(body);
            return;
        };
        if (stmts.len == 0) {
            try self.emitUnused("self");
            try self.emitUnused("ctx");
            return;
        }
        for (stmts) |stmt| {
            try self.emitStatement(stmt);
        }
    }

    fn emitStatement(self: *CodeGenerator, stmt: ast.Statement) !void {
        switch (stmt) {
            .variable_decl => |decl| {
                try self.emitIndent();
                // Always emit const unless parser explicitly marks as non-constant
                // AND the variable is known to be reassigned. For safety, default to const.
                try self.emit("const ");
                if (decl.var_names.len == 1) {
                    // Rename if it shadows a contract function
                    if (self.isContractFunction(decl.var_names[0])) {
                        var rename_buf: [128]u8 = undefined;
                        const renamed = std.fmt.bufPrint(&rename_buf, "{s}_local", .{decl.var_names[0]}) catch decl.var_names[0];
                        const renamed_dupe = self.allocator.dupe(u8, renamed) catch decl.var_names[0];
                        try self.param_renames.put(decl.var_names[0], renamed_dupe);
                        try self.emit(renamed_dupe);
                    } else {
                        try self.emit(decl.var_names[0]);
                    }
                } else {
                    // Tuple destructuring not natively supported in Zig — emit as multi-var
                    for (decl.var_names, 0..) |name, i| {
                        if (i > 0) try self.emit(", ");
                        try self.emit(name);
                    }
                }
                if (decl.type_name) |tn| {
                    try self.emit(": ");
                    try self.emit(type_mapper.mapType(tn));
                }
                if (decl.initial_value) |val| {
                    try self.emit(" = ");
                    try self.emitExpr(val);
                } else {
                    try self.emit(" = undefined");
                }
                try self.emitLine(";");
            },
            .expression_stmt => |es| {
                try self.emitIndent();
                try self.emitExpr(es.expr);
                try self.emitLine(";");
            },
            .if_stmt => |s| {
                try self.emitIndent();
                try self.emit("if (");
                try self.emitExpr(s.condition);
                try self.emitLine(") {");
                self.indent_level += 1;
                for (s.then_body) |inner| try self.emitStatement(inner);
                self.indent_level -= 1;
                if (s.else_body) |eb| {
                    try self.emitIndent();
                    try self.emitLine("} else {");
                    self.indent_level += 1;
                    for (eb) |inner| try self.emitStatement(inner);
                    self.indent_level -= 1;
                }
                try self.emitIndent();
                try self.emitLine("}");
            },
            .for_stmt => |s| {
                // Emit init outside loop
                if (s.init) |init_s| try self.emitStatement(init_s);
                try self.emitIndent();
                try self.emit("while (");
                if (s.condition) |c| try self.emitExpr(c) else try self.emit("true");
                try self.emit(") ");
                // Post expression as a continue expression
                if (s.post) |p| {
                    try self.emit(": (");
                    try self.emitExpr(p);
                    try self.emit(") ");
                }
                try self.emitLine("{");
                self.indent_level += 1;
                for (s.body) |inner| try self.emitStatement(inner);
                self.indent_level -= 1;
                try self.emitIndent();
                try self.emitLine("}");
            },
            .while_stmt => |s| {
                try self.emitIndent();
                try self.emit("while (");
                try self.emitExpr(s.condition);
                try self.emitLine(") {");
                self.indent_level += 1;
                for (s.body) |inner| try self.emitStatement(inner);
                self.indent_level -= 1;
                try self.emitIndent();
                try self.emitLine("}");
            },
            .do_while_stmt => |s| {
                try self.emitIndent();
                try self.emitLine("while (true) {");
                self.indent_level += 1;
                for (s.body) |inner| try self.emitStatement(inner);
                try self.emitIndent();
                try self.emit("if (!(");
                try self.emitExpr(s.condition);
                try self.emitLine(")) break;");
                self.indent_level -= 1;
                try self.emitIndent();
                try self.emitLine("}");
            },
            .return_stmt => |s| {
                try self.emitIndent();
                if (s.value) |val| {
                    try self.emit("return ");
                    try self.emitExpr(val);
                    try self.emitLine(";");
                } else {
                    try self.emitLine("return;");
                }
            },
            .emit_stmt => |s| {
                try self.emitIndent();
                try self.emit(s.event_name);
                try self.emit(".emit(ctx, .{");
                for (s.args, 0..) |arg, i| {
                    if (i > 0) try self.emit(", ");
                    try self.emitExpr(arg);
                }
                try self.emitLine("});");
            },
            .revert_stmt => |s| {
                try self.emitIndent();
                if (s.error_name) |name| {
                    try self.emit(name);
                    try self.emit(".raise(.{");
                    for (s.args, 0..) |arg, i| {
                        if (i > 0) try self.emit(", ");
                        try self.emitExpr(arg);
                    }
                    try self.emitLine("});");
                } else if (s.args.len > 0) {
                    try self.emit("sdk.revert(");
                    try self.emitExpr(s.args[0]);
                    try self.emitLine(");");
                } else {
                    try self.emitLine("sdk.revert(\"revert\");");
                }
            },
            .block => |s| {
                try self.emitIndent();
                try self.emitLine("{");
                self.indent_level += 1;
                for (s.statements) |inner| try self.emitStatement(inner);
                self.indent_level -= 1;
                try self.emitIndent();
                try self.emitLine("}");
            },
            .unchecked_block => |s| {
                try self.emitIndent();
                try self.emitLine("// unchecked {");
                try self.emitIndent();
                try self.emitLine("{");
                self.indent_level += 1;
                for (s.body) |inner| try self.emitStatement(inner);
                self.indent_level -= 1;
                try self.emitIndent();
                try self.emitLine("}");
            },
            .try_catch => |s| {
                try self.emitIndent();
                try self.emitLine("// try/catch — mapped to Zig error handling");
                try self.emitIndent();
                try self.emit("if (");
                try self.emitExpr(s.call_expr);
                try self.emitLine(") |result| {");
                self.indent_level += 1;
                try self.emitIndent();
                try self.emitLine("_ = result;");
                for (s.success_body) |inner| try self.emitStatement(inner);
                self.indent_level -= 1;
                for (s.catch_clauses) |clause| {
                    try self.emitIndent();
                    try self.emit("} else |");
                    if (clause.error_name) |name| try self.emit(name) else try self.emit("err");
                    try self.emitLine("| {");
                    self.indent_level += 1;
                    for (clause.body) |inner| try self.emitStatement(inner);
                    self.indent_level -= 1;
                }
                try self.emitIndent();
                try self.emitLine("}");
            },
            .assembly_block => |s| {
                try self.emitIndent();
                try self.emitLine("// assembly { ... } — Yul → Zig SDK mapping");
                // Parse and map common Yul operations to Zig SDK calls
                try self.emitYulBlock(s.raw_code);
            },
            .break_stmt => {
                try self.emitIndent();
                try self.emitLine("break;");
            },
            .continue_stmt => {
                try self.emitIndent();
                try self.emitLine("continue;");
            },
            .placeholder_stmt => {
                try self.emitIndent();
                try self.emitLine("// _; (modifier placeholder — body inserted here)");
            },
            .raw_statement => |s| {
                try self.emitIndent();
                try self.emit("// RAW: ");
                try self.emitLine(s.text);
            },
        }
    }

    // ========================================================================
    // Expression Emission
    // ========================================================================

    fn emitExpr(self: *CodeGenerator, expr: ast.Expression) !void {
        switch (expr) {
            .literal => |lit| {
                switch (lit.kind) {
                    .number_decimal, .number_hex => {
                        // Convert numeric literals: Solidity numbers → Uint256.fromU64(n) or direct
                        try self.emit("Uint256.fromU64(");
                        try self.emit(lit.value);
                        try self.emit(")");
                    },
                    .string_literal => {
                        try self.emit("\"");
                        try self.emit(lit.value);
                        try self.emit("\"");
                    },
                    .bool_true => try self.emit("true"),
                    .bool_false => try self.emit("false"),
                    .hex_string => {
                        try self.emit("\"\\x");
                        try self.emit(lit.value);
                        try self.emit("\"");
                    },
                    .unicode_string => {
                        try self.emit("\"");
                        try self.emit(lit.value);
                        try self.emit("\"");
                    },
                }
            },
            .identifier => |id| {
                // Map Solidity globals
                if (std.mem.eql(u8, id.name, "msg")) {
                    try self.emit("ctx");
                } else if (std.mem.eql(u8, id.name, "block")) {
                    try self.emit("ctx");
                } else if (std.mem.eql(u8, id.name, "tx")) {
                    try self.emit("ctx");
                } else if (std.mem.eql(u8, id.name, "this")) {
                    try self.emit("self");
                } else if (self.isStateVar(id.name)) {
                    try self.emit("self.");
                    try self.emit(id.name);
                    // Add .load() for StorageSlot-type state vars in read context
                    // Mappings/arrays/strings are accessed via .get()/.set() directly
                    if (!self.emitting_assign_target and self.isSlotStateVar(id.name)) {
                        try self.emit(".load(ctx.storage_backend)");
                    }
                } else if (self.param_renames.get(id.name)) |renamed| {
                    // Apply parameter rename (e.g., owner -> owner_param)
                    try self.emit(renamed);
                } else {
                    try self.emit(id.name);
                }
            },
            .binary_op => |bin| {
                // Map Solidity operators to SDK methods for Uint256
                try self.emitExpr(bin.left);
                switch (bin.op) {
                    .add => try self.emit(".checkedAdd("),
                    .sub => try self.emit(".checkedSub("),
                    .mul => try self.emit(".checkedMul("),
                    .div => try self.emit(".checkedDiv("),
                    .mod => try self.emit(".mod("),
                    .exp => try self.emit(".exp("),
                    .eq => try self.emit(".eql("),
                    .neq => {
                        // Zig can't use != on structs — use !x.eql(y)
                        const needs_method = true; // Address and Uint256 are structs
                        if (needs_method) {
                            try self.emit(".eql(");
                            try self.emitExpr(bin.right);
                            try self.emit(") == false");
                        } else {
                            try self.emit(" != ");
                            try self.emitExpr(bin.right);
                        }
                        return;
                    },
                    .lt => try self.emit(".lt("),
                    .gt => try self.emit(".gt("),
                    .lte => try self.emit(".lte("),
                    .gte => try self.emit(".gte("),
                    .and_ => {
                        try self.emit(" and ");
                        try self.emitExpr(bin.right);
                        return;
                    },
                    .or_ => {
                        try self.emit(" or ");
                        try self.emitExpr(bin.right);
                        return;
                    },
                    .bit_and => try self.emit(".bitwiseAnd("),
                    .bit_or => try self.emit(".bitwiseOr("),
                    .bit_xor => try self.emit(".bitwiseXor("),
                    .shl => try self.emit(".shl("),
                    .shr => try self.emit(".shr("),
                }
                try self.emitExpr(bin.right);
                try self.emit(")");
            },
            .unary_op => |un| {
                if (un.is_prefix) {
                    switch (un.op) {
                        .negate => try self.emit("-"),
                        .not => try self.emit("!"),
                        .bit_not => try self.emit("~"),
                        .increment => {
                            try self.emitExpr(un.operand);
                            try self.emit(" += 1");
                            return;
                        },
                        .decrement => {
                            try self.emitExpr(un.operand);
                            try self.emit(" -= 1");
                            return;
                        },
                        .delete => {
                            try self.emit("// delete ");
                            try self.emitExpr(un.operand);
                            return;
                        },
                    }
                    try self.emitExpr(un.operand);
                } else {
                    // Postfix: emit as statement-level side effect
                    try self.emitExpr(un.operand);
                    switch (un.op) {
                        .increment => try self.emit(" += 1"),
                        .decrement => try self.emit(" -= 1"),
                        else => {},
                    }
                }
            },
            .member_access => |ma| {
                try self.emitExpr(ma.object);
                try self.emit(".");
                // Map Solidity member names to Zig/SDK equivalents
                if (std.mem.eql(u8, ma.member, "sender")) try self.emit("msg_sender") else if (std.mem.eql(u8, ma.member, "value")) try self.emit("msg_value") else if (std.mem.eql(u8, ma.member, "data")) try self.emit("msg_data") else if (std.mem.eql(u8, ma.member, "timestamp")) try self.emit("block_timestamp") else if (std.mem.eql(u8, ma.member, "number")) try self.emit("block_number") else if (std.mem.eql(u8, ma.member, "coinbase")) try self.emit("block_coinbase") else if (std.mem.eql(u8, ma.member, "chainid")) try self.emit("block_chainid") else if (std.mem.eql(u8, ma.member, "origin")) try self.emit("tx_origin") else if (std.mem.eql(u8, ma.member, "gasprice")) try self.emit("tx_gasprice") else if (std.mem.eql(u8, ma.member, "balance")) try self.emit("getBalance()") else if (std.mem.eql(u8, ma.member, "length")) try self.emit("length(ctx.storage_backend)") else try self.emit(ma.member);
            },
            .function_call => |fc| {
                // Special-case require, assert
                if (fc.callee == .identifier) {
                    const name = fc.callee.identifier.name;
                    if (std.mem.eql(u8, name, "require")) {
                        if (fc.args.len >= 2) {
                            try self.emit("sdk.require(");
                            try self.emitExpr(fc.args[0]);
                            try self.emit(", ");
                            try self.emitExpr(fc.args[1]);
                            try self.emit(")");
                        } else if (fc.args.len == 1) {
                            try self.emit("sdk.requireBool(");
                            try self.emitExpr(fc.args[0]);
                            try self.emit(")");
                        }
                        return;
                    }
                    if (std.mem.eql(u8, name, "assert")) {
                        try self.emit("sdk.assert_(");
                        if (fc.args.len > 0) try self.emitExpr(fc.args[0]);
                        try self.emit(")");
                        return;
                    }
                    if (std.mem.eql(u8, name, "keccak256")) {
                        try self.emit("sdk.keccak256(");
                        for (fc.args, 0..) |arg, i| {
                            if (i > 0) try self.emit(", ");
                            try self.emitExpr(arg);
                        }
                        try self.emit(")");
                        return;
                    }
                    if (std.mem.eql(u8, name, "sha256")) {
                        try self.emit("sdk.sha256_hash(");
                        for (fc.args, 0..) |arg, i| {
                            if (i > 0) try self.emit(", ");
                            try self.emitExpr(arg);
                        }
                        try self.emit(")");
                        return;
                    }
                    if (std.mem.eql(u8, name, "ecrecover")) {
                        try self.emit("sdk.ecrecover(");
                        for (fc.args, 0..) |arg, i| {
                            if (i > 0) try self.emit(", ");
                            try self.emitExpr(arg);
                        }
                        try self.emit(")");
                        return;
                    }
                    if (std.mem.eql(u8, name, "addmod")) {
                        try self.emit("sdk.addmod(");
                        for (fc.args, 0..) |arg, i| {
                            if (i > 0) try self.emit(", ");
                            try self.emitExpr(arg);
                        }
                        try self.emit(")");
                        return;
                    }
                    if (std.mem.eql(u8, name, "mulmod")) {
                        try self.emit("sdk.mulmod_fn(");
                        for (fc.args, 0..) |arg, i| {
                            if (i > 0) try self.emit(", ");
                            try self.emitExpr(arg);
                        }
                        try self.emit(")");
                        return;
                    }
                }
                // Check if this is an internal function call (defined in the same contract)
                const is_internal = if (fc.callee == .identifier) blk: {
                    const callee_name = fc.callee.identifier.name;
                    for (self.current_contract_functions) |fn_name| {
                        if (std.mem.eql(u8, callee_name, fn_name)) break :blk true;
                    }
                    break :blk false;
                } else false;

                if (is_internal) {
                    // Internal function calls need self. prefix and ctx as first arg
                    try self.emit("self.");
                    try self.emitExpr(fc.callee);
                    try self.emit("(ctx");
                    for (fc.args) |arg| {
                        try self.emit(", ");
                        try self.emitExpr(arg);
                    }
                    try self.emit(")");
                } else {
                    try self.emitExpr(fc.callee);
                    try self.emit("(");
                    for (fc.args, 0..) |arg, i| {
                        if (i > 0) try self.emit(", ");
                        try self.emitExpr(arg);
                    }
                    try self.emit(")");
                }
            },
            .index_access => |ia| {
                try self.emitExpr(ia.object);
                try self.emit(".get(ctx.storage_backend, ");
                try self.emitExpr(ia.index);
                try self.emit(")");
            },
            .conditional => |cond| {
                try self.emit("if (");
                try self.emitExpr(cond.condition);
                try self.emit(") ");
                try self.emitExpr(cond.true_expr);
                try self.emit(" else ");
                try self.emitExpr(cond.false_expr);
            },
            .assignment => |a| {
                // Determine if this is a storage assignment
                const is_storage_target = self.isStorageTarget(a.target);

                if (is_storage_target) {
                    // Set flag to suppress .load() when emitting the target
                    self.emitting_assign_target = true;

                    // Storage assignment: use .store() / .set() APIs
                    if (a.target == .index_access) {
                        // Target is mapping[key] — use .set(backend, key, value)
                        const ia = a.target.index_access;
                        try self.emitExpr(ia.object);
                        try self.emit(".set(ctx.storage_backend, ");
                        self.emitting_assign_target = false; // key and value are reads
                        try self.emitExpr(ia.index);
                        try self.emit(", ");
                        if (a.op == .assign) {
                            try self.emitExpr(a.value);
                        } else {
                            // Compound: load, modify, store
                            self.emitting_assign_target = true;
                            try self.emitExpr(ia.object);
                            self.emitting_assign_target = false;
                            try self.emit(".get(ctx.storage_backend, ");
                            try self.emitExpr(ia.index);
                            try self.emit(")");
                            try self.emitCompoundOp(a.op);
                            try self.emitExpr(a.value);
                            try self.emit(")");
                        }
                        try self.emit(")");
                    } else {
                        // Target is a state variable — use .store(backend, value)
                        try self.emitExpr(a.target);
                        self.emitting_assign_target = false;
                        try self.emit(".store(ctx.storage_backend, ");
                        if (a.op == .assign) {
                            try self.emitExpr(a.value);
                        } else {
                            // Compound: load, modify, store
                            self.emitting_assign_target = true;
                            try self.emitExpr(a.target);
                            self.emitting_assign_target = false;
                            try self.emit(".load(ctx.storage_backend)");
                            try self.emitCompoundOp(a.op);
                            try self.emitExpr(a.value);
                            try self.emit(")");
                        }
                        try self.emit(")");
                    }
                    self.emitting_assign_target = false;
                } else {
                    // Non-storage assignment: emit normally
                    try self.emitExpr(a.target);
                    if (a.op == .assign) {
                        try self.emit(" = ");
                        try self.emitExpr(a.value);
                    } else {
                        try self.emit(" ");
                        try self.emit(a.op.toString());
                        try self.emit(" ");
                        try self.emitExpr(a.value);
                    }
                }
            },
            .type_cast => |tc| {
                const zig_type = type_mapper.mapType(tc.target_type);
                try self.emit(zig_type);
                if (std.mem.eql(u8, zig_type, "sdk.Address")) {
                    try self.emit(".fromUint(");
                } else if (std.mem.eql(u8, zig_type, "sdk.Uint256") or std.mem.eql(u8, zig_type, "Uint256")) {
                    try self.emit(".fromU64(@intCast(");
                } else {
                    try self.emit("(");
                }
                try self.emitExpr(tc.operand);
                if (std.mem.eql(u8, zig_type, "sdk.Uint256") or std.mem.eql(u8, zig_type, "Uint256")) {
                    try self.emit("))");
                } else {
                    try self.emit(")");
                }
            },
            .new_expression => |ne| {
                try self.emit(ne.type_name);
                try self.emit(".init(");
                for (ne.args, 0..) |arg, i| {
                    if (i > 0) try self.emit(", ");
                    try self.emitExpr(arg);
                }
                try self.emit(")");
            },
            .tuple => |t| {
                try self.emit(".{");
                for (t.elements, 0..) |elem_opt, i| {
                    if (i > 0) try self.emit(", ");
                    if (elem_opt) |elem| {
                        try self.emitExpr(elem);
                    } else {
                        try self.emit("_");
                    }
                }
                try self.emit("}");
            },
            .elementary_type => |et| {
                try self.emit(type_mapper.mapType(et.type_name));
            },
            .array_literal => |al| {
                try self.emit(".{");
                for (al.elements, 0..) |elem, i| {
                    if (i > 0) try self.emit(", ");
                    try self.emitExpr(elem);
                }
                try self.emit("}");
            },
            .state_var_ref => |svr| {
                try self.emit("self.");
                try self.emit(svr.name);
            },
            .delete_expr => |de| {
                try self.emit("// delete ");
                try self.emitExpr(de.operand);
            },
            .emit_expr => |ee| {
                try self.emit(ee.event_name);
                try self.emit(".emit(ctx, .{");
                for (ee.args, 0..) |arg, i| {
                    if (i > 0) try self.emit(", ");
                    try self.emitExpr(arg);
                }
                try self.emit("})");
            },
            .abi_call => |ac| {
                if (std.mem.eql(u8, ac.function, "encode")) {
                    try self.emit("sdk.abi_encode(self.allocator, .{");
                } else if (std.mem.eql(u8, ac.function, "encodePacked")) {
                    try self.emit("sdk.abi_encodePacked(self.allocator, .{");
                } else if (std.mem.eql(u8, ac.function, "encodeWithSelector")) {
                    try self.emit("sdk.abi_encodeWithSelector(self.allocator, ");
                    if (ac.args.len > 0) {
                        try self.emitExpr(ac.args[0]);
                        try self.emit(", .{");
                        for (ac.args[1..], 0..) |arg, i| {
                            if (i > 0) try self.emit(", ");
                            try self.emitExpr(arg);
                        }
                    }
                } else if (std.mem.eql(u8, ac.function, "decode")) {
                    try self.emit("sdk.abi_decode(");
                    for (ac.args, 0..) |arg, i| {
                        if (i > 0) try self.emit(", ");
                        try self.emitExpr(arg);
                    }
                    try self.emit(")");
                    return;
                } else {
                    try self.emit("sdk.abi_encode(self.allocator, .{");
                }
                for (ac.args, 0..) |arg, i| {
                    if (i > 0) try self.emit(", ");
                    try self.emitExpr(arg);
                }
                try self.emit("})");
            },
            .type_info => |ti| {
                if (std.mem.eql(u8, ti.member, "max")) {
                    try self.emit(type_mapper.mapType(ti.target_type));
                    try self.emit(".MAX");
                } else if (std.mem.eql(u8, ti.member, "min")) {
                    try self.emit(type_mapper.mapType(ti.target_type));
                    try self.emit(".MIN");
                } else {
                    try self.emit("@typeInfo(");
                    try self.emit(type_mapper.mapType(ti.target_type));
                    try self.emit(").");
                    try self.emit(ti.member);
                }
            },
        }
    }

    // ========================================================================
    // Helpers
    // ========================================================================

    fn emitRawBody(self: *CodeGenerator, body: []const u8) !void {
        var trimmed = body;
        if (trimmed.len > 0 and trimmed[0] == '{') trimmed = trimmed[1..];
        if (trimmed.len > 0 and trimmed[trimmed.len - 1] == '}') trimmed = trimmed[0 .. trimmed.len - 1];
        trimmed = std.mem.trim(u8, trimmed, " \t\n\r");
        if (trimmed.len == 0) {
            try self.emitUnused("self");
            try self.emitUnused("ctx");
            return;
        }
        try self.emitIndent();
        try self.emitLine("// TODO: Transpile function body (parse error fallback)");
        var lines = std.mem.splitSequence(u8, trimmed, "\n");
        while (lines.next()) |line| {
            const l = std.mem.trim(u8, line, " \t\r");
            if (l.len == 0) continue;
            try self.emitIndent();
            try self.emit("// ");
            try self.emitLine(l);
        }
    }

    fn emitRawExpression(self: *CodeGenerator, expr: []const u8) !void {
        try self.emit(expr);
    }

    /// Emit a Uint256 constant value from a raw Solidity literal.
    /// Handles: plain integers ("7"), scientific notation ("69e9"), hex ("0xff").
    fn emitUint256Constant(self: *CodeGenerator, val: []const u8) !void {
        const trimmed = std.mem.trim(u8, val, " \t\r\n");

        // Check for scientific notation: NUMeEXP (e.g., "69e9", "1e18")
        if (std.mem.indexOfScalar(u8, trimmed, 'e')) |e_pos| {
            // Parse mantissa and exponent
            const mantissa_str = trimmed[0..e_pos];
            const exp_str = trimmed[e_pos + 1 ..];
            const mantissa = std.fmt.parseInt(u64, mantissa_str, 10) catch {
                // Fallback
                try self.emit("Uint256.fromU64(");
                try self.emit(trimmed);
                try self.emit(")");
                return;
            };
            const exponent = std.fmt.parseInt(u32, exp_str, 10) catch {
                try self.emit("Uint256.fromU64(");
                try self.emit(trimmed);
                try self.emit(")");
                return;
            };

            // Compute value: mantissa * 10^exponent
            // For values that fit in u64 (< 1.8e19), use fromU64
            // For larger values, use fromU128 or chain multiply
            if (exponent <= 19) {
                var power: u128 = 1;
                for (0..exponent) |_| power *= 10;
                const result = @as(u128, mantissa) * power;
                if (result <= std.math.maxInt(u64)) {
                    try self.emit("Uint256.fromU64(");
                    var num_buf: [20]u8 = undefined;
                    const num_str = std.fmt.bufPrint(&num_buf, "{d}", .{@as(u64, @intCast(result))}) catch "0";
                    try self.emit(num_str);
                    try self.emit(")");
                } else if (result <= std.math.maxInt(u128)) {
                    try self.emit("Uint256.fromU128(");
                    var num_buf: [40]u8 = undefined;
                    const num_str = std.fmt.bufPrint(&num_buf, "{d}", .{result}) catch "0";
                    try self.emit(num_str);
                    try self.emit(")");
                } else {
                    try self.emit("Uint256.fromU64(");
                    try self.emit(mantissa_str);
                    try self.emit(").checkedMul(Uint256.fromU64(10).exp(Uint256.fromU64(");
                    try self.emit(exp_str);
                    try self.emit(")))");
                }
            } else {
                // Very large exponent — use runtime computation
                try self.emit("Uint256.fromU64(");
                try self.emit(mantissa_str);
                try self.emit(").checkedMul(Uint256.fromU64(10).exp(Uint256.fromU64(");
                try self.emit(exp_str);
                try self.emit(")))");
            }
            return;
        }

        // Check for hex: 0x...
        if (trimmed.len >= 2 and trimmed[0] == '0' and (trimmed[1] == 'x' or trimmed[1] == 'X')) {
            try self.emit("Uint256.fromHex(\"");
            try self.emit(trimmed);
            try self.emit("\")");
            return;
        }

        // Plain integer literal
        // Check if it fits in u64
        if (std.fmt.parseInt(u64, trimmed, 10)) |_| {
            try self.emit("Uint256.fromU64(");
            try self.emit(trimmed);
            try self.emit(")");
        } else |_| {
            // Try u128
            if (std.fmt.parseInt(u128, trimmed, 10)) |_| {
                try self.emit("Uint256.fromU128(");
                try self.emit(trimmed);
                try self.emit(")");
            } else |_| {
                // Fallback: emit raw
                try self.emit(trimmed);
            }
        }
    }

    fn emitParamName(self: *CodeGenerator, name: []const u8) !void {
        if (name.len > 0) try self.emit(name) else try self.emit("_");
    }

    fn emitUnused(self: *CodeGenerator, name: []const u8) !void {
        try self.emitIndent();
        try self.emit("_ = ");
        try self.emit(name);
        try self.emitLine(";");
    }

    /// Check if identifier is a state variable name in the current contract
    fn isStateVar(self: *const CodeGenerator, name: []const u8) bool {
        for (self.current_state_vars) |sv_name| {
            if (std.mem.eql(u8, name, sv_name)) return true;
        }
        return false;
    }

    /// Check if a state variable is a StorageSlot type (not mapping/array/string/bytes)
    /// Only StorageSlot vars need .load()/.store() — mappings use .get()/.set() directly
    fn isSlotStateVar(self: *const CodeGenerator, name: []const u8) bool {
        for (self.current_state_vars, 0..) |sv_name, i| {
            if (std.mem.eql(u8, name, sv_name)) {
                if (i < self.current_state_var_types.len) {
                    const sol_type = self.current_state_var_types[i];
                    // Mapping, array, string, bytes are NOT slot types
                    if (std.mem.startsWith(u8, sol_type, "mapping(") or
                        std.mem.startsWith(u8, sol_type, "mapping ") or
                        std.mem.indexOf(u8, sol_type, "[") != null or
                        std.mem.eql(u8, sol_type, "string") or
                        std.mem.eql(u8, sol_type, "bytes"))
                    {
                        return false;
                    }
                }
                return true;
            }
        }
        return false;
    }

    /// Check if an expression target refers to a storage location
    /// (state variable, index into state variable mapping)
    fn isStorageTarget(self: *const CodeGenerator, expr: ast.Expression) bool {
        return switch (expr) {
            .identifier => |id| self.isStateVar(id.name),
            .state_var_ref => true,
            .index_access => |ia| self.isStorageTarget(ia.object),
            .member_access => |ma| self.isStorageTarget(ma.object),
            else => false,
        };
    }

    /// Check if a name matches a function in the current contract
    fn isContractFunction(self: *const CodeGenerator, name: []const u8) bool {
        for (self.current_contract_functions) |fn_name| {
            if (std.mem.eql(u8, name, fn_name)) return true;
        }
        return false;
    }

    /// Emit the SDK method call suffix for compound assignment operators
    /// e.g., += becomes .checkedAdd(, -= becomes .checkedSub(
    fn emitCompoundOp(self: *CodeGenerator, op: ast.AssignmentOp) !void {
        switch (op) {
            .add_assign => try self.emit(".checkedAdd("),
            .sub_assign => try self.emit(".checkedSub("),
            .mul_assign => try self.emit(".checkedMul("),
            .div_assign => try self.emit(".checkedDiv("),
            .mod_assign => try self.emit(".mod("),
            .or_assign => try self.emit(".bitwiseOr("),
            .and_assign => try self.emit(".bitwiseAnd("),
            .xor_assign => try self.emit(".bitwiseXor("),
            .shl_assign => try self.emit(".shl("),
            .shr_assign => try self.emit(".shr("),
            .assign => {}, // Should not reach here
        }
    }

    fn emit(self: *CodeGenerator, text: []const u8) !void {
        try self.output.appendSlice(self.allocator, text);
    }

    fn emitLine(self: *CodeGenerator, text: []const u8) !void {
        try self.output.appendSlice(self.allocator, text);
        try self.output.append(self.allocator, '\n');
    }

    fn emitIndent(self: *CodeGenerator) !void {
        var i: usize = 0;
        while (i < self.indent_level) : (i += 1) {
            try self.output.appendSlice(self.allocator, "    ");
        }
    }

    // ========================================================================
    // PHASE 5: Advanced Codegen Patterns
    // ========================================================================

    /// Emit a resolved mapping type: mapping(K => V) → sdk.StorageMapping(K_zig, V_zig)
    /// Handles nested mappings recursively
    fn emitMappingType(self: *CodeGenerator, sol_type: []const u8) !void {
        if (type_mapper.parseMappingTypes(sol_type)) |mt| {
            const key_zig = type_mapper.mapType(mt.key);
            try self.emit("sdk.StorageMapping(");
            try self.emit(key_zig);
            try self.emit(", ");
            // Check if value is also a mapping (nested)
            const value_trimmed = std.mem.trim(u8, mt.value, " \t\n\r");
            if (std.mem.startsWith(u8, value_trimmed, "mapping(")) {
                try self.emitMappingType(value_trimmed);
            } else {
                try self.emit(type_mapper.mapType(value_trimmed));
            }
            try self.emit(")");
        } else {
            // Fallback if parsing fails
            try self.emit("sdk.StorageMapping(sdk.Address, sdk.Uint256)");
        }
    }

    /// Generate storage layout comments showing slot assignments
    /// Follows Solidity's sequential slot assignment rules
    fn generateStorageLayout(self: *CodeGenerator, contract: parser.ContractDef) !void {
        if (contract.state_variables.items.len == 0) return;

        try self.emitIndent();
        try self.emitLine("// Storage Layout:");
        var slot: usize = 0;
        for (contract.state_variables.items) |sv| {
            if (sv.mutability == .constant or sv.mutability == .immutable) continue;

            try self.emitIndent();
            try self.emit("//   slot ");

            // Emit slot number as decimal string
            var buf: [20]u8 = undefined;
            const slot_str = std.fmt.bufPrint(&buf, "{d}", .{slot}) catch "?";
            try self.emit(slot_str);

            try self.emit(": ");
            try self.emit(sv.name);
            try self.emit(" (");
            try self.emit(sv.type_name);
            try self.emitLine(")");

            // Mappings and dynamic arrays use 1 slot for the base
            slot += 1;
        }
        try self.emitLine("");
    }

    /// Generate dispatch table for function selector routing
    /// Emits a comptime-accessible array of selector → handler mappings
    fn generateDispatchTable(self: *CodeGenerator, contract: parser.ContractDef) !void {
        // Count dispatchable functions
        var count: usize = 0;
        for (contract.functions.items) |func| {
            if (func.kind == .constructor or func.kind == .receive or func.kind == .fallback) continue;
            if (func.visibility != .external and func.visibility != .public) continue;
            count += 1;
        }
        if (count == 0) return;

        try self.emitIndent();
        try self.emitLine("// Function dispatch table");
        try self.emitIndent();
        try self.emitLine("pub const __function_selectors = .{");
        self.indent_level += 1;

        for (contract.functions.items) |func| {
            if (func.kind == .constructor or func.kind == .receive or func.kind == .fallback) continue;
            if (func.visibility != .external and func.visibility != .public) continue;

            // Compute selector
            const sel = selector.computeFunctionSelector(self.allocator, func) catch [4]u8{ 0, 0, 0, 0 };
            const hex = selector.selectorToHex(sel);

            try self.emitIndent();
            try self.emit(".{ .selector = \"");
            try self.emit(&hex);
            try self.emit("\", .name = \"");
            try self.emit(func.name);
            try self.emitLine("\" },");
        }

        self.indent_level -= 1;
        try self.emitIndent();
        try self.emitLine("};");
        try self.emitLine("");

        // Generate dispatch function
        try self.emitIndent();
        try self.emitLine("pub fn dispatch(self: *@This(), ctx: *sdk.ExecutionContext, calldata: []const u8) ![]u8 {");
        self.indent_level += 1;

        try self.emitIndent();
        try self.emitLine("if (calldata.len < 4) {");
        self.indent_level += 1;
        try self.emitIndent();
        try self.emitLine("// No selector — try receive/fallback");
        try self.emitIndent();
        try self.emitLine("_ = self;");
        try self.emitIndent();
        try self.emitLine("_ = ctx;");
        try self.emitIndent();
        try self.emitLine("return error.NoFallback;");
        self.indent_level -= 1;
        try self.emitIndent();
        try self.emitLine("}");

        try self.emitIndent();
        try self.emitLine("const sel = calldata[0..4].*;");
        try self.emitIndent();
        try self.emitLine("_ = sel;");
        try self.emitIndent();
        try self.emitLine("// Match selector against dispatch table");
        try self.emitIndent();
        try self.emitLine("// (comptime unrolled matching generated above)");
        try self.emitIndent();
        try self.emitLine("return error.UnknownSelector;");

        self.indent_level -= 1;
        try self.emitIndent();
        try self.emitLine("}");
        try self.emitLine("");
    }

    // ========================================================================
    // Yul Assembly → Zig SDK Mapping
    // ========================================================================

    fn emitYulBlock(self: *CodeGenerator, raw_code: []const u8) !void {
        // Tokenize Yul code by lines and map each statement
        var lines = std.mem.splitScalar(u8, raw_code, '\n');
        while (lines.next()) |raw_line| {
            const line = std.mem.trim(u8, raw_line, " \t\r");
            if (line.len == 0 or std.mem.eql(u8, line, "{") or std.mem.eql(u8, line, "}")) continue;

            try self.emitIndent();

            // Map known Yul operations to Zig SDK calls
            if (std.mem.startsWith(u8, line, "sstore(")) {
                // sstore(slot, value) → ctx.storage_backend.store(slot, value)
                try self.emit("ctx.storage_backend.store(");
                try self.emit(line["sstore(".len .. line.len - 1]);
                try self.emitLine(");");
            } else if (std.mem.startsWith(u8, line, "let ") or std.mem.startsWith(u8, line, "mstore(")) {
                if (std.mem.startsWith(u8, line, "mstore(")) {
                    // mstore(offset, value) → memory write
                    try self.emit("// mstore: ");
                    try self.emitLine(line);
                } else {
                    // let x := sload(slot) → const x = ctx.storage_backend.load(slot)
                    if (std.mem.indexOf(u8, line, ":= sload(")) |_| {
                        const var_end = std.mem.indexOf(u8, line, " :=") orelse line.len;
                        const var_name = line["let ".len..var_end];
                        const sload_start = std.mem.indexOf(u8, line, "sload(").? + "sload(".len;
                        const sload_end = std.mem.indexOf(u8, line[sload_start..], ")").? + sload_start;
                        try self.emit("const ");
                        try self.emit(var_name);
                        try self.emit(" = ctx.storage_backend.load(");
                        try self.emit(line[sload_start..sload_end]);
                        try self.emitLine(");");
                    } else if (std.mem.indexOf(u8, line, ":= caller()")) |_| {
                        const var_end = std.mem.indexOf(u8, line, " :=") orelse line.len;
                        try self.emit("const ");
                        try self.emit(line["let ".len..var_end]);
                        try self.emitLine(" = ctx.msg_sender;");
                    } else if (std.mem.indexOf(u8, line, ":= callvalue()")) |_| {
                        const var_end = std.mem.indexOf(u8, line, " :=") orelse line.len;
                        try self.emit("const ");
                        try self.emit(line["let ".len..var_end]);
                        try self.emitLine(" = ctx.msg_value;");
                    } else if (std.mem.indexOf(u8, line, ":= calldataload(")) |_| {
                        const var_end = std.mem.indexOf(u8, line, " :=") orelse line.len;
                        try self.emit("const ");
                        try self.emit(line["let ".len..var_end]);
                        try self.emitLine(" = sdk.calldataLoad(ctx);");
                    } else if (std.mem.indexOf(u8, line, ":= calldatasize()")) |_| {
                        const var_end = std.mem.indexOf(u8, line, " :=") orelse line.len;
                        try self.emit("const ");
                        try self.emit(line["let ".len..var_end]);
                        try self.emitLine(" = ctx.msg_data.len;");
                    } else if (std.mem.indexOf(u8, line, ":= balance(")) |_| {
                        const var_end = std.mem.indexOf(u8, line, " :=") orelse line.len;
                        try self.emit("const ");
                        try self.emit(line["let ".len..var_end]);
                        try self.emitLine(" = ctx.getBalance();");
                    } else if (std.mem.indexOf(u8, line, ":= extcodesize(")) |_| {
                        const var_end = std.mem.indexOf(u8, line, " :=") orelse line.len;
                        try self.emit("const ");
                        try self.emit(line["let ".len..var_end]);
                        try self.emitLine(" = sdk.getExtCodeSize(ctx);");
                    } else {
                        // Generic let binding
                        try self.emit("// yul: ");
                        try self.emitLine(line);
                    }
                }
            } else if (std.mem.startsWith(u8, line, "return(")) {
                // return(offset, size) → return memory slice
                try self.emitLine("return; // Yul return");
            } else if (std.mem.startsWith(u8, line, "revert(")) {
                // revert(offset, size) → sdk.revert
                try self.emitLine("sdk.revert(\"revert\"); // Yul revert");
            } else if (std.mem.startsWith(u8, line, "selfdestruct(")) {
                try self.emitLine("sdk.selfDestruct(ctx); // selfdestruct");
            } else if (std.mem.startsWith(u8, line, "log")) {
                // log0..log4 → event emission
                try self.emit("// Yul log: ");
                try self.emitLine(line);
            } else if (std.mem.startsWith(u8, line, "if ")) {
                // Yul if → Zig if
                try self.emit("if (");
                const body_start = std.mem.indexOf(u8, line, "{") orelse line.len;
                try self.emit(line["if ".len..body_start]);
                try self.emitLine(") {");
            } else {
                // Unknown Yul — emit as comment for manual review
                try self.emit("// yul: ");
                try self.emitLine(line);
            }
        }
    }
};
